sudo: required
dist: trusty
language: node_js
node_js:
  - '9'
addons:
  apt:
    packages:
    - libunwind8
os:
  - linux
  - osx
osx_image: xcode9.3
before_install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - git clone https://github.com/dotnet/cli.git
  - ./cli/scripts/obtain/dotnet-install.sh --channel release/2.1 --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - npm run publish
